# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picode2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QSize,QCoreApplication,QMetaObject
from PySide2.QtWidgets import QWidget,QPushButton,QTextBrowser,QLabel,QMenuBar,QMenu,QStatusBar
from PySide2.QtGui import QFont
from  PySide2.QtWidgets import QMainWindow
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 673)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        ###按钮：打开选择需要伪装的图片的对话框
        self.fileToCode = QPushButton(self.centralwidget)
        self.fileToCode.setGeometry(10, 50, 80, 41)
        self.fileToCode.setIconSize(QSize(12, 16))
        self.fileToCode.setObjectName("fileToCode")
        ###按钮：打开选择需要去伪装的对话框
        self.fileToDecode = QPushButton(self.centralwidget)
        self.fileToDecode.setGeometry(10, 400, 80, 41)
        self.fileToDecode.setObjectName("fileToDecode")
        ###按钮：选择缩放倍率，2倍
        self.codeTimes2 = QPushButton(self.centralwidget)
        self.codeTimes2.setGeometry(215, 470, 100, 30)
        self.codeTimes2.setIconSize(QSize(12, 16))
        self.codeTimes2.setObjectName("codeTimes2")
        ###按钮：选择缩放倍率，4倍
        self.codeTimes4 = QPushButton(self.centralwidget)
        self.codeTimes4.setGeometry(320, 470, 80, 30)
        self.codeTimes4.setIconSize(QSize(12, 16))
        self.codeTimes4.setObjectName("codeTimes4")
        ###按钮：选择缩放倍率，6倍
        self.codeTimes6 = QPushButton(self.centralwidget)
        self.codeTimes6.setGeometry(410, 470, 80, 30)
        self.codeTimes6.setIconSize(QSize(12, 16))
        self.codeTimes6.setObjectName("codeTimes6")
        ###按钮：选择缩放倍率，8倍
        self.codeTimes8 = QPushButton(self.centralwidget)
        self.codeTimes8.setGeometry(495, 470, 80, 30)
        self.codeTimes8.setIconSize(QSize(12, 16))
        self.codeTimes8.setObjectName("codeTimes8")
        ###显示需要伪装的图片的地址
        self.toCodeAddress = QTextBrowser(self.centralwidget)
        self.toCodeAddress.setGeometry(100, 50, 400, 40)
        self.toCodeAddress.setObjectName("toCodeAddress")
        ###显示底片的地址
        self.toBackPicAddress = QTextBrowser(self.centralwidget)
        self.toBackPicAddress.setGeometry(100, 100, 400, 40)
        self.toBackPicAddress.setObjectName("toCodeAddress")
        ###显示需要去伪装的图片的地址
        self.toDecodedAddress = QTextBrowser(self.centralwidget)
        self.toDecodedAddress.setGeometry(100, 400, 400, 40)
        self.toDecodedAddress.setObjectName("toDecodedAddress")

        ###按钮：开始伪装图片
        self.toCode = QPushButton(self.centralwidget)
        self.toCode.setGeometry(520, 50, 60, 40)
        self.toCode.setObjectName("toCode")
        ###
        self.defaultColor = QPushButton(self.centralwidget)
        self.defaultColor.setGeometry(520, 100, 200, 40)
        self.defaultColor.setObjectName("defaultColor")
        ###按钮：打开选择底片的对话框
        self.fileToBackPic = QPushButton(self.centralwidget)
        self.fileToBackPic.setGeometry(10, 100, 80, 40)
        self.fileToBackPic.setObjectName("fileToBackBic")
        ###按钮：保存已伪装的图片
        self.toSaveC = QPushButton(self.centralwidget)
        self.toSaveC.setGeometry(600, 50, 120, 40)
        self.toSaveC.setObjectName("toSaveC")
        ###按钮：保存去伪装的图片
        self.toSaveD = QPushButton(self.centralwidget)
        self.toSaveD.setGeometry(600, 400, 120, 40)
        self.toSaveD.setObjectName("toSaveC")
        ###按钮：开始去伪装
        self.toDecode = QPushButton(self.centralwidget)
        self.toDecode.setGeometry(520, 400, 60, 40)
        self.toDecode.setObjectName("toDecode")
        ###
        self.CodetimesTxt = QLabel(self.centralwidget)
        self.CodetimesTxt.setGeometry(10, 470, 200, 30)
        font = QFont()
        font.setPointSize(12)
        self.CodetimesTxt.setFont(font)
        self.CodetimesTxt.setLineWidth(2)
        self.CodetimesTxt.setObjectName("CodetimesTxt")
        self.CodetimesTxt.setStyleSheet("background-color: rgb(255, 255, 255);")
        ###
        self.auth = QTextBrowser(self.centralwidget)
        self.auth.setGeometry(10, 10, 700, 30)
        font = QFont()
        font.setPointSize(12)
        self.auth.setFont(font)
        self.auth.setLineWidth(2)
        self.auth.setObjectName("CodetimesTxt")
        ###
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(0, 0, 761, 23)
        self.menubar.setObjectName("menubar")
        self.menufile = QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menufile.addSeparator()
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "picode"))
        self.fileToCode.setText(_translate("MainWindow", "选择要加密\n"
"的图片"))
        self.fileToDecode.setText(_translate("MainWindow", "选择要解密\n"
"的图片"))
        self.fileToBackPic.setText(_translate("MainWindow", "选择要底片\n"
))
        self.toCode.setText(_translate("MainWindow", "加密"))
        self.defaultColor.setText(_translate("MainWindow", "使用默认底片（随机纯色图片）"))
        self.toDecode.setText(_translate("MainWindow", "解密"))
        self.toSaveC.setText(_translate("MainWindow", "保存已加密的文件"))
        self.toSaveD.setText(_translate("MainWindow", "保存已解密的文件"))
        self.codeTimes2.setText(_translate("MainWindow", "2倍（2X2默认）"))
        self.codeTimes4.setText(_translate("MainWindow", "4倍（4X4）"))
        self.codeTimes6.setText(_translate("MainWindow", "6倍（6X6）"))
        self.codeTimes8.setText(_translate("MainWindow", "8倍（8X8）"))
        self.CodetimesTxt.setText(_translate("MainWindow", " 图片缩放倍数（长&宽）::"))
        self.auth.setText(_translate("MainWindow", " 作者：@escort_ss 发布地址：https://www.bilibili.com/read/cv10102558"))
class Window(Ui_MainWindow, QMainWindow):
    def __init__(self):
        super(Window, self).__init__()
        self.setupUi(self)
if __name__ == '__main__':
    app = QApplication(sys.argv)
    mywindow = Window()
    mywindow.show()
    sys.exit(app.exec_())
