# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picode2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileToCode = QtWidgets.QPushButton(self.centralwidget)
        self.fileToCode.setGeometry(QtCore.QRect(10, 50, 80, 41))
        self.fileToCode.setIconSize(QtCore.QSize(12, 16))
        self.fileToCode.setObjectName("fileToCode")
        self.fileToDecode = QtWidgets.QPushButton(self.centralwidget)
        self.fileToDecode.setGeometry(QtCore.QRect(10, 400, 80, 41))
        self.fileToDecode.setObjectName("fileToDecode")
        ###
        self.codeTimes2 = QtWidgets.QPushButton(self.centralwidget)
        self.codeTimes2.setGeometry(QtCore.QRect(215, 470, 100, 30))
        self.codeTimes2.setIconSize(QtCore.QSize(12, 16))
        self.codeTimes2.setObjectName("codeTimes2")
        ###
        self.codeTimes4 = QtWidgets.QPushButton(self.centralwidget)
        self.codeTimes4.setGeometry(QtCore.QRect(320, 470, 80, 30))
        self.codeTimes4.setIconSize(QtCore.QSize(12, 16))
        self.codeTimes4.setObjectName("codeTimes4")
        ###
        self.codeTimes6 = QtWidgets.QPushButton(self.centralwidget)
        self.codeTimes6.setGeometry(QtCore.QRect(410, 470, 80, 30))
        self.codeTimes6.setIconSize(QtCore.QSize(12, 16))
        self.codeTimes6.setObjectName("codeTimes6")
        ###
        self.codeTimes8 = QtWidgets.QPushButton(self.centralwidget)
        self.codeTimes8.setGeometry(QtCore.QRect(495, 470, 80, 30))
        self.codeTimes8.setIconSize(QtCore.QSize(12, 16))
        self.codeTimes8.setObjectName("codeTimes8")
        ###
        self.toCodeAddress = QtWidgets.QTextBrowser(self.centralwidget)
        self.toCodeAddress.setGeometry(QtCore.QRect(100, 50, 400, 40))
        self.toCodeAddress.setObjectName("toCodeAddress")
        self.toDecodedAddress = QtWidgets.QTextBrowser(self.centralwidget)
        self.toDecodedAddress.setGeometry(QtCore.QRect(100, 400, 400, 40))
        self.toDecodedAddress.setObjectName("toDecodedAddress")
        ###
        self.toCode = QtWidgets.QPushButton(self.centralwidget)
        self.toCode.setGeometry(QtCore.QRect(520, 50, 60, 40))
        self.toCode.setObjectName("toCode")
        ###
        self.toSaveC = QtWidgets.QPushButton(self.centralwidget)
        self.toSaveC.setGeometry(QtCore.QRect(600, 50, 120, 40))
        self.toSaveC.setObjectName("toSaveC")
        ###
        self.toSaveD = QtWidgets.QPushButton(self.centralwidget)
        self.toSaveD.setGeometry(QtCore.QRect(600, 400, 120, 40))
        self.toSaveD.setObjectName("toSaveC")
        ###
        self.toDecode = QtWidgets.QPushButton(self.centralwidget)
        self.toDecode.setGeometry(QtCore.QRect(520, 400, 60, 40))
        self.toDecode.setObjectName("toDecode")
        ###
        self.CodetimesTxt = QtWidgets.QLabel(self.centralwidget)
        self.CodetimesTxt.setGeometry(QtCore.QRect(10, 470, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CodetimesTxt.setFont(font)
        self.CodetimesTxt.setLineWidth(2)
        self.CodetimesTxt.setObjectName("CodetimesTxt")
        self.CodetimesTxt.setStyleSheet("background-color: rgb(255, 255, 255);")
        ###
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menufile.addSeparator()
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "picode"))
        self.fileToCode.setText(_translate("MainWindow", "选择要加密\n"
"的图片"))
        self.fileToDecode.setText(_translate("MainWindow", "选择要解密\n"
"的图片"))
        self.toCode.setText(_translate("MainWindow", "加密"))
        self.toDecode.setText(_translate("MainWindow", "解密"))
        self.toSaveC.setText(_translate("MainWindow", "保存已加密的文件"))
        self.toSaveD.setText(_translate("MainWindow", "保存已解密的文件"))
        self.codeTimes2.setText(_translate("MainWindow", "2倍（2X2默认）"))
        self.codeTimes4.setText(_translate("MainWindow", "4倍（4X4）"))
        self.codeTimes6.setText(_translate("MainWindow", "6倍（6X6）"))
        self.codeTimes8.setText(_translate("MainWindow", "8倍（8X8）"))
        self.CodetimesTxt.setText(_translate("MainWindow", " 图片缩放倍数（长&宽）::"))
