# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picode2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileToCode = QtWidgets.QPushButton(self.centralwidget)
        self.fileToCode.setGeometry(QtCore.QRect(10, 420, 81, 41))
        self.fileToCode.setIconSize(QtCore.QSize(12, 16))
        self.fileToCode.setObjectName("fileToCode")
        self.fileToDecode = QtWidgets.QPushButton(self.centralwidget)
        self.fileToDecode.setGeometry(QtCore.QRect(380, 420, 75, 41))
        self.fileToDecode.setObjectName("fileToDecode")
        self.toCodeAddress = QtWidgets.QTextBrowser(self.centralwidget)
        self.toCodeAddress.setGeometry(QtCore.QRect(100, 430, 231, 31))
        self.toCodeAddress.setObjectName("toCodeAddress")
        self.toDecodedAddress = QtWidgets.QTextBrowser(self.centralwidget)
        self.toDecodedAddress.setGeometry(QtCore.QRect(470, 430, 256, 31))
        self.toDecodedAddress.setObjectName("toDecodedAddress")
        self.toCode = QtWidgets.QPushButton(self.centralwidget)
        self.toCode.setGeometry(QtCore.QRect(10, 470, 81, 31))
        self.toCode.setObjectName("toCode")
        self.toDecode = QtWidgets.QPushButton(self.centralwidget)
        self.toDecode.setGeometry(QtCore.QRect(380, 470, 75, 31))
        self.toDecode.setObjectName("toDecode")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(343, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 145, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 230, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.toCodePic = QtWidgets.QLabel(self.centralwidget)
        self.toCodePic.setScaledContents(True)

        self.toCodePic.setGeometry(QtCore.QRect(80, 60, 210, 297))
        self.toCodePic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toCodePic.setText("显示图片")
        self.toCodePic.setObjectName("toCodePic")
        self.toDecodePic = QtWidgets.QLabel(self.centralwidget)
        self.toDecodePic.setScaledContents(True)
        self.toDecodePic.setGeometry(QtCore.QRect(470, 60, 210, 297))
        self.toDecodePic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.toDecodePic.setText("显示图片")
        self.toDecodePic.setObjectName("toDecodePic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menufile.addSeparator()
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "picode"))
        self.fileToCode.setText(_translate("MainWindow", "选择要加密\n"
"的图片"))
        self.fileToDecode.setText(_translate("MainWindow", "选择要解密\n"
"的图片"))
        self.toCode.setText(_translate("MainWindow", "加密并保存"))
        self.toDecode.setText(_translate("MainWindow", "解密并保存"))
        self.label.setText(_translate("MainWindow", "→→→→"))
        self.label_2.setText(_translate("MainWindow", "←←←←"))
        self.label_3.setText(_translate("MainWindow", "加密"))
        self.label_4.setText(_translate("MainWindow", "解密"))
